python train_imgreid_xent_htri.py -d pclreid \
    -a vmgn_hgnn \
    --optim adam \
    --lr 0.0002 \
    --max-epoch 80 \
    --train-batch 64 \
    --test-batch 100 \
    --stepsize 20 40 60 \
    --global-branch \
    --soft-margin \
    --label-smooth \
    --warmup \
    --save-dir ./log/resnet50-xent \
    --gpu-devices 5 \
    --eval-step 1 \
    --dist-metric cosine \